In [1]:
%load_ext autoreload
%autoreload 2
from pathlib import Path
from skimage.io import imread
import matplotlib.pyplot as plt
import pigleg_cv
import shutil

/opt/conda/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


NOTE! Installing ujson may make loading annotations faster.


2023-12-16 12:11:05,508 - /webapps/piglegsurgery/piglegcv/incision_detection_mmdet.py - DEBUG - mmdet.version=2.25.0
2023-12-16 12:11:05,508 - /webapps/piglegsurgery/piglegcv/incision_detection_mmdet.py - DEBUG - 11.7
2023-12-16 12:11:05,509 - /webapps/piglegsurgery/piglegcv/incision_detection_mmdet.py - DEBUG - GCC 9.4


1.12.0a0+8a1a93a True


In [2]:
!pwd

/webapps/piglegsurgery/piglegcv


In [3]:
import torch
torch.cuda.is_available()

True

In [50]:
!nvidia-smi

Sat Dec 16 21:48:46 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.103.01   Driver Version: 470.103.01   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:42:00.0 Off |                  N/A |
|  0%   38C    P8     9W / 250W |   4442MiB / 11175MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [5]:
torch.__version__

'1.12.0a0+8a1a93a'

In [6]:
Path("~/.cache/torch/hub/checkpoints/").expanduser().exists()

True

In [7]:
!ls ~/.cache/torch/hub/checkpoints/

yolox_x_8x8_300e_coco_20211126_140254-1ef88d67.pth


In [8]:
# pip install mmcv-full

# Run whole video processing

In [53]:
is_microsurgery = False
test_first_seconds=False
n_stitches = 3

patch = "*/Anasto*.mp4"
# patch = "*/2023_10_11_B-Grübbel_Mareike_Fortlaufende_Transkutannaht.mov"
patch = "*/Einzel.MOV"
patch = "test_4.mp4"; n_stitches=0
# patch = "*/*micro_01*.mp4"
# patch = "2023_10_11_B_Seltmann_Charlotte_fortlaufende_Transcutannaht.mp4"; n_stitches=5
# patch = "Katharina_Einzelknopfnaht"; n_stitches=3


img_pths = list(Path("../piglegsurgeryweb/media/upload/").glob(f"*/*{patch}*"))
img_pths[0]

PosixPath('../piglegsurgeryweb/media/upload/20231213-100825_pigleg_test_4_8b0ed51a4ea6b6cfcd6ab6f9b4e3b5a7309f4234/pigleg_test_4.mp4')

In [54]:
outputdir = "./del_test_video_output/"

# original outputdir
# outputdir = list(list(Path("../piglegsurgeryweb/media/").glob(f"*/*{patch}*.zip"))[0].parent.glob("*/meta.json"))[0].parent
# outputdir = outputdir.absolute().resolve()
# outputdir

In [55]:
# this is to test it on processed video
# outputdir = Path("del_test_video_output_copy")
# shutil.rmtree(outputdir, ignore_errors=True)
# patch = "2023_10_11_B_Seltmann_Charlotte_fortlaufende_Transcutannaht.mp4"
# patch = "Katharina_Einzelknopfnaht"
# img_pths = list(Path("../piglegsurgeryweb/media/").glob(f"**/*{patch}*.zip"))
# print(img_pths)
# shutil.copytree(str(img_pths[0].parent), str(outputdir))

# outputdir = list(outputdir.glob("*/*"))[0].parent

# img_pths = list(Path("../piglegsurgeryweb/media/upload/").glob(f"*/*{patch}*"))
# print(img_pths[0])
# # img_pths[0].parent
# # outputdir = Path("/webapps/piglegsurgery/piglegsurgeryweb/media/SA_20231011-191116_doqinglbsdnj").glob("**/*")
# # list(outputdir)
# outputdir

## Do whole processing together


In [ ]:
dcv = pigleg_cv.DoComputerVision(img_pths[0], outputdir, test_first_seconds=test_first_seconds, is_microsurgery=is_microsurgery)
dcv.run()

2023-12-16 21:55:43.379 | INFO     | pigleg_cv:run:89 - CV processing started on ../piglegsurgeryweb/media/upload/20231213-100825_pigleg_test_4_8b0ed51a4ea6b6cfcd6ab6f9b4e3b5a7309f4234/pigleg_test_4.mp4, outputdir=del_test_video_output
2023-12-16 21:55:43.380 | DEBUG    | pigleg_cv:run_video_processing:195 - Running video processing...
2023-12-16 21:55:43.381 | DEBUG    | pigleg_cv:get_parameters_for_crop_rotate_rescale:268 - device=cuda
2023-12-16 21:55:43.414 | DEBUG    | run_perpendicular:get_frame_to_process:166 - 152
2023-12-16 21:55:43.737 | DEBUG    | run_qr:get_bboxes:41 - [[     1113.3      165.34      1252.3      308.42     0.99033]
 [     403.41      157.77      541.42      293.09     0.98839]
 [     236.06           0      1645.7      1041.7     0.12932]
 [     411.57      387.71      1534.8      1051.1    0.087532]]
2023-12-16 21:55:43.905 | DEBUG    | run_qr:bbox_info_extraction_from_frame:81 - qr code text = 'Resolution 30 mm'
2023-12-16 21:55:43.906 | DEBUG    | run_qr:

Fusing layers... 
IDetect.fuse
load checkpoint from local path: /webapps/piglegsurgery/piglegcv/resources/incision_detection_models/220326_234659_mmdet.pth


2023-12-16 21:55:44,423 - /webapps/piglegsurgery/piglegcv/incision_detection_mmdet.py - DEBUG - number of detected incisions = 1
2023-12-16 21:55:44.426 | DEBUG    | pigleg_cv:get_parameters_for_crop_rotate_rescale:279 - {'bbox_scene_area': [227.45236206054688,
                     0.0,
                     1696.503662109375,
                     1080.0,
                     0.4435734450817108],
 'box': [[410, 287], [532, 286], [535, 164], [411, 164]],
 'incision_bboxes': [[780.993896484375,
                      706.4788208007812,
                      1069.618408203125,
                      785.2167358398438,
                      0.9762410521507263]],
 'incision_bboxes_old': [[763.6923828125,
                          683.0553588867188,
                          1078.682861328125,
                          798.51025390625,
                          0.9964717626571655]],
 'is_detected': True,
 'pix_size': 0.0002458933791571777,
 'pix_size_method': 'QR',
 'pix_size_single_frame_detec

Fusing layers... 
IDetect.fuse


2023-12-16 21:55:46.027 | DEBUG    | run_qr:get_bboxes:41 - [[     417.58      61.622      470.16      116.34     0.99174]
 [     152.72      59.157      203.08      109.99     0.98808]
 [     115.56      4.9073      639.24      383.87     0.14154]
 [     63.891      167.25      610.52      396.37     0.12254]]
2023-12-16 21:55:46.179 | DEBUG    | run_qr:bbox_info_extraction_from_frame:81 - qr code text = 'Resolution 30 mm'
2023-12-16 21:55:46.180 | DEBUG    | run_qr:bbox_info_extraction_from_frame:81 - qr code text = 'Scissors 30 mm'
2023-12-16 21:55:46.181 | DEBUG    | run_qr:bbox_info_extraction_from_frame:149 - {'pix_size_method': 'QR', 'is_detected': True, 'box': [[154, 61], [154, 107], [199, 106], [200, 61]], 'pix_size': 0.0006521739130434782, 'incision_bboxes': [[293.6681823730469, 265.6772155761719, 397.66607666015625, 292.37109375, 0.9791364669799805]], 'qr_size': 0.03, 'size_by_scene': 0.00041666666666666664, 'text': 'Resolution 30 mm', 'pix_size_single_frame_detector_m': 0.0

Fusing layers... 
IDetect.fuse
load checkpoint from local path: /webapps/piglegsurgery/piglegcv/resources/incision_detection_models/220326_234659_mmdet.pth


2023-12-16 21:55:46,863 - /webapps/piglegsurgery/piglegcv/incision_detection_mmdet.py - DEBUG - number of detected incisions = 1
2023-12-16 21:55:46.865 | DEBUG    | run_perpendicular:main_perpendicular:301 - len(imgs)=1
2023-12-16 21:55:46.898 | DEBUG    | tools:save_json:17 - Writing 'del_test_video_output/perpendicular_0.json'
2023-12-16 21:55:46.899 | DEBUG    | tools:save_json:26 - old keys: ['intersections', 'alphas']
2023-12-16 21:55:46.900 | DEBUG    | tools:save_json:28 - updated keys: ['intersections', 'alphas']
2023-12-16 21:55:47,312 - /webapps/piglegsurgery/piglegcv/stitch_detection_mmdet.py - DEBUG - cfg_path=PosixPath('stitch_detection_mmdet_config.py'), True
2023-12-16 21:55:47,313 - /webapps/piglegsurgery/piglegcv/stitch_detection_mmdet.py - DEBUG - checkpoint_path=PosixPath('/webapps/piglegsurgery/piglegcv/resources/stitch_detection_models/model.pth'), True


load checkpoint from local path: /webapps/piglegsurgery/piglegcv/resources/stitch_detection_models/model.pth


/home/appuser/mmdetection/mmdet/datasets/utils.py:66: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(
2023-12-16 21:55:47.814 | DEBUG    | tools:save_json:17 - Writing 'del_test_video_output/stitch_detection_0.json'
2023-12-16 21:55:47.815 | DEBUG    | tools:save_json:26 - old keys: ['stitch_labels', 'stitch_bboxes']
2023-12-16 21:55:47.816 | DEBUG    | tools:save_json:28 - updated keys: ['stitch_labels', 'stitch_bboxes']
2023-12-16 21:55:47,817 - /webapps/piglegsurgery/piglegcv/stitch_detection_mmdet.py - DEBUG - number of detected stitches = 5
2023-12-16 21:55:47,818 - /webapps/piglegsurgery/piglegcv/stitch_detection_mmdet.py - DEBUG - Stitch detection finished, boxes in: del_test_video_output/stitch_detection_0.json
2023-12-16 21:55:47,898 - /webapps/piglegsurgery/piglegcv/stitch_detection_mmdet.py - DEBUG - R-squared upper line: 0.

load checkpoint from local path: /webapps/piglegsurgery/piglegcv/resources/tracker_model_bytetrack/epoch.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: ema_detector_backbone_stem_conv_conv_weight, ema_detector_backbone_stem_conv_bn_weight, ema_detector_backbone_stem_conv_bn_bias, ema_detector_backbone_stem_conv_bn_running_mean, ema_detector_backbone_stem_conv_bn_running_var, ema_detector_backbone_stem_conv_bn_num_batches_tracked, ema_detector_backbone_stage1_0_conv_weight, ema_detector_backbone_stage1_0_bn_weight, ema_detector_backbone_stage1_0_bn_bias, ema_detector_backbone_stage1_0_bn_running_mean, ema_detector_backbone_stage1_0_bn_running_var, ema_detector_backbone_stage1_0_bn_num_batches_tracked, ema_detector_backbone_stage1_1_main_conv_conv_weight, ema_detector_backbone_stage1_1_main_conv_bn_weight, ema_detector_backbone_stage1_1_main_conv_bn_bias, ema_detector_backbone_stage1_1_main_conv_bn_running_mean, ema_detector_backbone_stage1

2023-12-16 21:55:53,855 - mmdet - INFO - image shape: height=800, width=1440 in YOLOX.__init__
2023-12-16 21:55:53,879 - /webapps/piglegsurgery/piglegcv/incision_detection_mmdet.py - INFO - initialize YOLOX with init_cfg {'type': 'Pretrained', 'checkpoint': 'https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_x_8x8_300e_coco/yolox_x_8x8_300e_coco_20211126_140254-1ef88d67.pth'}
2023-12-16 21:55:53,879 - mmcv - INFO - load model from: https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_x_8x8_300e_coco/yolox_x_8x8_300e_coco_20211126_140254-1ef88d67.pth
2023-12-16 21:55:53,880 - mmcv - INFO - load checkpoint from http path: https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_x_8x8_300e_coco/yolox_x_8x8_300e_coco_20211126_140254-1ef88d67.pth
2023-12-16 21:55:54,151 - mmcv - WARNING - The model and loaded state dict do not match exactly

size mismatch for bbox_head.multi_level_conv_cls.0.weight: copying a param with shape torch.Size([80, 320, 1, 1]) from checkpoint, t

load checkpoint from local path: /webapps/piglegsurgery/piglegcv/resources/tracker_model_bytetrack_hands_tools/epoch_2.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: ema_detector_backbone_stem_conv_conv_weight, ema_detector_backbone_stem_conv_bn_weight, ema_detector_backbone_stem_conv_bn_bias, ema_detector_backbone_stem_conv_bn_running_mean, ema_detector_backbone_stem_conv_bn_running_var, ema_detector_backbone_stem_conv_bn_num_batches_tracked, ema_detector_backbone_stage1_0_conv_weight, ema_detector_backbone_stage1_0_bn_weight, ema_detector_backbone_stage1_0_bn_bias, ema_detector_backbone_stage1_0_bn_running_mean, ema_detector_backbone_stage1_0_bn_running_var, ema_detector_backbone_stage1_0_bn_num_batches_tracked, ema_detector_backbone_stage1_1_main_conv_conv_weight, ema_detector_backbone_stage1_1_main_conv_bn_weight, ema_detector_backbone_stage1_1_main_conv_bn_bias, ema_detector_backbone_stage1_1_main_conv_bn_running_mean, ema_detector_b

2023-12-16 21:55:57.199 | DEBUG    | run_tracker_bytetrack:main_tracker_bytetrack:69 - hash_hex='0xc0c33f3f3f27df3453b7dba0eb7b317e55fc489ad4e6b6dd3e94b772d6970c8a86cf37dc0b69d6f4'
2023-12-16 21:55:57.201 | DEBUG    | run_tracker_bytetrack:main_tracker_bytetrack:82 - Cannot read tracks.json. Exception: Expecting value: line 1 column 56794 (char 56793)
2023-12-16 21:55:57.214 | DEBUG    | run_tracker_bytetrack:main_tracker_bytetrack:94 - Processing frame 0 by tracker
2023-12-16 22:00:56.829 | DEBUG    | run_tracker_bytetrack:main_tracker_bytetrack:94 - Processing frame 50 by tracker
2023-12-16 22:06:00.638 | DEBUG    | run_tracker_bytetrack:main_tracker_bytetrack:94 - Processing frame 100 by tracker


In [12]:
# report_data = dcv.make_report()