In [1]:
%load_ext autoreload
%autoreload 2
from pathlib import Path
from skimage.io import imread
import matplotlib.pyplot as plt
import pigleg_cv
import shutil

/opt/conda/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


NOTE! Installing ujson may make loading annotations faster.


2023-12-15 12:31:29,887 - /webapps/piglegsurgery/piglegcv/incision_detection_mmdet.py - DEBUG - mmdet.version=2.25.0
2023-12-15 12:31:29,888 - /webapps/piglegsurgery/piglegcv/incision_detection_mmdet.py - DEBUG - 11.7
2023-12-15 12:31:29,889 - /webapps/piglegsurgery/piglegcv/incision_detection_mmdet.py - DEBUG - GCC 9.4


1.12.0a0+8a1a93a True


In [2]:
!pwd

/webapps/piglegsurgery/piglegcv


In [3]:
import torch
torch.cuda.is_available()

True

In [4]:
!nvidia-smi

Fri Dec 15 12:31:30 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.103.01   Driver Version: 470.103.01   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:42:00.0 Off |                  N/A |
|  0%   49C    P8    10W / 250W |    320MiB / 11175MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [5]:
torch.__version__

'1.12.0a0+8a1a93a'

In [6]:
Path("~/.cache/torch/hub/checkpoints/").expanduser().exists()

True

In [7]:
!ls ~/.cache/torch/hub/checkpoints/

yolox_x_8x8_300e_coco_20211126_140254-1ef88d67.pth


In [8]:
# pip install mmcv-full

# Run whole video processing

In [9]:
outputdir = "./del_test_video_output/"

In [10]:
patch = "*/Anasto*.mp4"
# patch = "*/2023_10_11_B-Grübbel_Mareike_Fortlaufende_Transkutannaht.mov"
patch = "*/Einzel.MOV"
patch = "*/*test_4.mp4"
patch = "*/*micro_01*.mp4"
patch = "*/2023_10_11_B_Seltmann_Charlotte_fortlaufende_Transcutannaht.mp4"
patch = "Katharina_Einzelknopfnaht"
is_microsurgery = False
test_first_seconds=False
n_stitches = 3

img_pths = list(Path("../piglegsurgeryweb/media/upload/").glob(f"*/*{patch}*"))
img_pths[0]

PosixPath('../piglegsurgeryweb/media/upload/20220707-190320_Good-03_11_2021_B_Holzmu_ller_Katharina_Einzelknopfnaht_7ba22f6773dc133ce7a06321ee9f507b9cb0f653/Good-03_11_2021_B_Holzmu_ller_Katharina_Einzelknopfnaht.mp4')

## Do whole processing together


In [11]:
outputdir = "./del_test_video_output/"
dcv = pigleg_cv.DoComputerVision(img_pths[0], outputdir, test_first_seconds=test_first_seconds, is_microsurgery=is_microsurgery)
dcv.run()

2023-12-15 12:31:30.824 | INFO     | pigleg_cv:run:89 - CV processing started on ../piglegsurgeryweb/media/upload/20220707-190320_Good-03_11_2021_B_Holzmu_ller_Katharina_Einzelknopfnaht_7ba22f6773dc133ce7a06321ee9f507b9cb0f653/Good-03_11_2021_B_Holzmu_ller_Katharina_Einzelknopfnaht.mp4, outputdir=del_test_video_output
2023-12-15 12:31:30.825 | DEBUG    | pigleg_cv:run_video_processing:178 - Running video processing...
2023-12-15 12:31:30.825 | DEBUG    | pigleg_cv:get_parameters_for_crop_rotate_rescale:251 - device=cuda
2023-12-15 12:31:30.844 | DEBUG    | run_perpendicular:get_frame_to_process:166 - 6177
/home/appuser/mmdetection/mmdet/datasets/utils.py:66: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(
2023-12-15 12:31:33.612 | DEBUG    | run_qr:get_bboxes:41 - [[     1328.5      287.58      1485.1      451.83     0.97808]
 [     10

Fusing layers... 
IDetect.fuse


2023-12-15 12:31:34.138 | DEBUG    | run_qr:get_bboxes:41 - [[     1328.3      287.36      1485.4      452.05     0.97652]
 [      169.1      70.752      1562.6      1183.3     0.15209]
 [     252.07       594.7        1297      1178.2     0.11663]]
2023-12-15 12:31:34.312 | DEBUG    | run_qr:bbox_info_extraction_from_frame:81 - qr code text = 'QR scale pigleg'
2023-12-15 12:31:34.313 | DEBUG    | run_qr:bbox_info_extraction_from_frame:149 - {'pix_size_method': 'QR', 'is_detected': True, 'box': [[1329, 345], [1384, 445], [1484, 392], [1428, 293]], 'pix_size': 0.0002365782953426947, 'incision_bboxes': [], 'qr_size': 0.027, 'size_by_scene': 0.00015625, 'text': 'QR scale pigleg', 'pix_size_single_frame_detector_m': 0.00023486253771573708, 'bbox_scene_area': [224.78338623046875, 55.20570373535156, 1595.5701904296875, 1148.9517822265625, 0.4195505678653717], 'qr_scissors_frame_detected': False, 'qr_bboxes_SFD': [[1328.322509765625, 287.3583068847656, 1485.363525390625, 452.04559326171875, 0

Fusing layers... 
IDetect.fuse


2023-12-15 12:31:34.651 | DEBUG    | run_qr:get_bboxes:41 - [[     1328.4      287.37      1485.3      451.91     0.97589]
 [     111.26      45.528      1535.6        1174     0.15299]
 [     251.56      593.65      1299.8      1179.3     0.11767]]
2023-12-15 12:31:34.823 | DEBUG    | run_qr:bbox_info_extraction_from_frame:81 - qr code text = 'QR scale pigleg'
2023-12-15 12:31:34.824 | DEBUG    | run_qr:bbox_info_extraction_from_frame:149 - {'pix_size_method': 'QR', 'is_detected': True, 'box': [[1329, 345], [1384, 445], [1484, 392], [1427, 293]], 'pix_size': 0.0002365782953426947, 'incision_bboxes': [], 'qr_size': 0.027, 'size_by_scene': 0.00015625, 'text': 'QR scale pigleg', 'pix_size_single_frame_detector_m': 0.0002350760815128885, 'bbox_scene_area': [229.44712829589844, 32.0108642578125, 1560.897705078125, 1177.0782470703125, 0.39952459931373596], 'qr_scissors_frame_detected': False, 'qr_bboxes_SFD': [[1328.3602294921875, 287.37261962890625, 1485.31640625, 451.9090576171875, 0.9758

Fusing layers... 
IDetect.fuse


2023-12-15 12:31:35.146 | DEBUG    | run_qr:get_bboxes:41 - [[       1329      289.24      1483.4      450.37     0.98092]
 [     165.65      70.152      1560.2      1180.6     0.15171]
 [     271.72      593.13      1143.2      1176.3    0.068642]]
2023-12-15 12:31:35.316 | DEBUG    | run_qr:bbox_info_extraction_from_frame:81 - qr code text = 'QR scale pigleg'
2023-12-15 12:31:35.317 | DEBUG    | run_qr:bbox_info_extraction_from_frame:149 - {'pix_size_method': 'QR', 'is_detected': True, 'box': [[1329, 345], [1384, 446], [1483, 392], [1427, 295]], 'pix_size': 0.00023477373272987406, 'incision_bboxes': [], 'qr_size': 0.027, 'size_by_scene': 0.00015625, 'text': 'QR scale pigleg', 'pix_size_single_frame_detector_m': 0.00023411089077563418, 'bbox_scene_area': [219.70486450195312, 52.792327880859375, 1554.739013671875, 1168.380615234375, 0.4208371043205261], 'qr_scissors_frame_detected': False, 'qr_bboxes_SFD': [[1329.015869140625, 289.2392883300781, 1483.3677978515625, 450.36669921875, 0.9

Fusing layers... 
IDetect.fuse


2023-12-15 12:31:35.666 | DEBUG    | run_qr:get_bboxes:41 - [[     1328.7      286.99      1485.5      451.62      0.9761]
 [     235.35      2.2842        1721      1106.6     0.15683]
 [     166.61      512.38      1402.6      1184.8      0.1268]]
2023-12-15 12:31:35.833 | DEBUG    | run_qr:bbox_info_extraction_from_frame:81 - qr code text = 'QR scale pigleg'
2023-12-15 12:31:35.834 | DEBUG    | run_qr:bbox_info_extraction_from_frame:149 - {'pix_size_method': 'QR', 'is_detected': True, 'box': [[1329, 345], [1384, 445], [1483, 392], [1427, 293]], 'pix_size': 0.0002365782953426947, 'incision_bboxes': [[613.271484375, 901.325927734375, 938.23974609375, 1012.3321533203125, 0.8951320052146912]], 'qr_size': 0.027, 'size_by_scene': 0.00015625, 'text': 'QR scale pigleg', 'pix_size_single_frame_detector_m': 0.00023392629883425538, 'bbox_scene_area': [230.18495178222656, 45.01597595214844, 1558.912109375, 1175.4052734375, 0.43627968430519104], 'qr_scissors_frame_detected': False, 'qr_bboxes_SF

Fusing layers... 
IDetect.fuse
load checkpoint from local path: /webapps/piglegsurgery/piglegcv/resources/incision_detection_models/220326_234659_mmdet.pth


2023-12-15 12:31:36,499 - /webapps/piglegsurgery/piglegcv/incision_detection_mmdet.py - DEBUG - number of detected incisions = 1
2023-12-15 12:31:36.502 | DEBUG    | pigleg_cv:get_parameters_for_crop_rotate_rescale:262 - {'bbox_scene_area': [230.18495178222656,
                     45.01597595214844,
                     1558.912109375,
                     1175.4052734375,
                     0.43627968430519104],
 'box': [[1329, 345], [1384, 445], [1483, 392], [1427, 293]],
 'incision_bboxes': [[613.271484375,
                      901.325927734375,
                      938.23974609375,
                      1012.3321533203125,
                      0.8951320052146912]],
 'incision_bboxes_old': [[611.1397705078125,
                          898.7380981445312,
                          925.5891723632812,
                          1020.3345947265625,
                          0.9957913160324097]],
 'is_detected': True,
 'pix_size': 0.0002365782953426947,
 'pix_size_method': 'QR',
 'p

Fusing layers... 
IDetect.fuse


2023-12-15 12:32:00.073 | DEBUG    | run_qr:get_bboxes:41 - [[     497.98      108.61      556.67      168.73     0.98006]
 [     38.188      19.108       576.7      446.15     0.13706]
 [     94.357      219.44      425.12      441.25    0.064228]]
2023-12-15 12:32:00.217 | DEBUG    | run_qr:bbox_info_extraction_from_frame:81 - qr code text = 'QR scale pigleg'
2023-12-15 12:32:00.218 | DEBUG    | run_qr:bbox_info_extraction_from_frame:149 - {'pix_size_method': 'QR', 'is_detected': True, 'box': [[498, 129], [519, 167], [556, 147], [535, 110]], 'pix_size': 0.0006218821436015863, 'incision_bboxes': [], 'qr_size': 0.027, 'size_by_scene': 0.00041666666666666664, 'text': 'QR scale pigleg', 'pix_size_single_frame_detector_m': 0.0006160274742549718, 'bbox_scene_area': [71.2433853149414, 15.643844604492188, 672.4984130859375, 422.2715759277344, 0.4020305871963501], 'qr_scissors_frame_detected': False, 'qr_bboxes_SFD': [[497.9844970703125, 108.60578918457031, 556.6707153320312, 168.732696533203

Fusing layers... 
IDetect.fuse


2023-12-15 12:32:00.452 | DEBUG    | run_qr:get_bboxes:41 - [[     497.97       108.6      556.71      168.78     0.98006]
 [     36.685      18.277      575.25      446.04     0.13544]
 [     93.367      218.92      422.99      441.17    0.059314]]
2023-12-15 12:32:00.597 | DEBUG    | run_qr:bbox_info_extraction_from_frame:81 - qr code text = 'QR scale pigleg'
2023-12-15 12:32:00.600 | DEBUG    | run_qr:bbox_info_extraction_from_frame:149 - {'pix_size_method': 'QR', 'is_detected': True, 'box': [[498, 129], [519, 167], [556, 147], [535, 110]], 'pix_size': 0.0006218821436015863, 'incision_bboxes': [], 'qr_size': 0.027, 'size_by_scene': 0.00041666666666666664, 'text': 'QR scale pigleg', 'pix_size_single_frame_detector_m': 0.0006158671965173156, 'bbox_scene_area': [69.5113525390625, 15.50035285949707, 680.6153564453125, 424.7549133300781, 0.41419652104377747], 'qr_scissors_frame_detected': False, 'qr_bboxes_SFD': [[497.9712829589844, 108.59620666503906, 556.7144165039062, 168.783187866210

Fusing layers... 
IDetect.fuse


2023-12-15 12:32:00.837 | DEBUG    | run_qr:get_bboxes:41 - [[     498.09      108.56      556.76       168.7     0.97932]
 [     37.636      18.102      576.14      445.24     0.13397]
 [     96.496      219.58      426.31      441.06    0.063377]]
2023-12-15 12:32:00.977 | DEBUG    | run_qr:bbox_info_extraction_from_frame:81 - qr code text = 'QR scale pigleg'
2023-12-15 12:32:00.978 | DEBUG    | run_qr:bbox_info_extraction_from_frame:149 - {'pix_size_method': 'QR', 'is_detected': True, 'box': [[498, 129], [519, 167], [556, 147], [535, 110]], 'pix_size': 0.0006218821436015863, 'incision_bboxes': [], 'qr_size': 0.027, 'size_by_scene': 0.00041666666666666664, 'text': 'QR scale pigleg', 'pix_size_single_frame_detector_m': 0.0006157070438175547, 'bbox_scene_area': [70.04209899902344, 15.142936706542969, 676.2048950195312, 421.2061767578125, 0.4043543040752411], 'qr_scissors_frame_detected': False, 'qr_bboxes_SFD': [[498.0854797363281, 108.55525207519531, 556.7601928710938, 168.69946289062

Fusing layers... 
IDetect.fuse


2023-12-15 12:32:01.226 | DEBUG    | run_qr:get_bboxes:41 - [[     498.11       108.5      556.64      168.76     0.97879]
 [     38.702      18.243      578.38       447.3     0.15043]
 [     48.288      237.41      559.16      445.31    0.079742]]
2023-12-15 12:32:01.514 | DEBUG    | run_qr:bbox_info_extraction_from_frame:81 - qr code text = 'QR scale pigleg'
2023-12-15 12:32:01.515 | DEBUG    | run_qr:bbox_info_extraction_from_frame:149 - {'pix_size_method': 'QR', 'is_detected': True, 'box': [[498, 129], [519, 167], [556, 147], [535, 109]], 'pix_size': 0.0006218821436015863, 'incision_bboxes': [[230.8421173095703, 338.629150390625, 351.29827880859375, 379.03460693359375, 0.9215223789215088]], 'qr_size': 0.027, 'size_by_scene': 0.00041666666666666664, 'text': 'QR scale pigleg', 'pix_size_single_frame_detector_m': 0.000615387112882045, 'bbox_scene_area': [86.10791778564453, 7.424560546875, 588.289306640625, 445.79473876953125, 0.4219725430011749], 'qr_scissors_frame_detected': False, 

Fusing layers... 
IDetect.fuse


2023-12-15 12:32:01.722 | DEBUG    | run_qr:get_bboxes:41 - [[     498.11       108.5      556.64      168.76     0.97879]
 [     38.702      18.243      578.38       447.3     0.15043]
 [     48.288      237.41      559.16      445.31    0.079742]]
2023-12-15 12:32:01.869 | DEBUG    | run_qr:bbox_info_extraction_from_frame:81 - qr code text = 'QR scale pigleg'
2023-12-15 12:32:01.871 | DEBUG    | run_qr:bbox_info_extraction_from_frame:149 - {'pix_size_method': 'QR', 'is_detected': True, 'box': [[498, 129], [519, 167], [556, 147], [535, 109]], 'pix_size': 0.0006218821436015863, 'incision_bboxes': [[230.8421173095703, 338.629150390625, 351.29827880859375, 379.03460693359375, 0.9215223789215088]], 'qr_size': 0.027, 'size_by_scene': 0.00041666666666666664, 'text': 'QR scale pigleg', 'pix_size_single_frame_detector_m': 0.000615387112882045, 'bbox_scene_area': [86.10791778564453, 7.424560546875, 588.289306640625, 445.79473876953125, 0.4219725430011749], 'qr_scissors_frame_detected': False, 

Fusing layers... 
IDetect.fuse
load checkpoint from local path: /webapps/piglegsurgery/piglegcv/resources/incision_detection_models/220326_234659_mmdet.pth


2023-12-15 12:32:02,588 - /webapps/piglegsurgery/piglegcv/incision_detection_mmdet.py - DEBUG - number of detected incisions = 0
2023-12-15 12:32:02.590 | DEBUG    | run_perpendicular:main_perpendicular:301 - len(imgs)=0
2023-12-15 12:32:02.591 | DEBUG    | pigleg_cv:run_image_processing:136 - Perpendicular finished.
2023-12-15 12:32:02.592 | DEBUG    | pigleg_cv:run_video_processing:194 - Single frame processing on cropped mediafile finished in 3.160672426223755s.
2023-12-15 12:32:02.592 | DEBUG    | pigleg_cv:run_video_processing:196 - Image processing finished in 3.161336898803711s.
2023-12-15 12:32:03,985 - mmdet - INFO - image shape: height=800, width=1440 in YOLOX.__init__
2023-12-15 12:32:04,009 - /webapps/piglegsurgery/piglegcv/incision_detection_mmdet.py - INFO - initialize YOLOX with init_cfg {'type': 'Pretrained', 'checkpoint': 'https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_x_8x8_300e_coco/yolox_x_8x8_300e_coco_20211126_140254-1ef88d67.pth'}
2023-12-15 12:32:04

load checkpoint from local path: /webapps/piglegsurgery/piglegcv/resources/tracker_model_bytetrack/epoch.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: ema_detector_backbone_stem_conv_conv_weight, ema_detector_backbone_stem_conv_bn_weight, ema_detector_backbone_stem_conv_bn_bias, ema_detector_backbone_stem_conv_bn_running_mean, ema_detector_backbone_stem_conv_bn_running_var, ema_detector_backbone_stem_conv_bn_num_batches_tracked, ema_detector_backbone_stage1_0_conv_weight, ema_detector_backbone_stage1_0_bn_weight, ema_detector_backbone_stage1_0_bn_bias, ema_detector_backbone_stage1_0_bn_running_mean, ema_detector_backbone_stage1_0_bn_running_var, ema_detector_backbone_stage1_0_bn_num_batches_tracked, ema_detector_backbone_stage1_1_main_conv_conv_weight, ema_detector_backbone_stage1_1_main_conv_bn_weight, ema_detector_backbone_stage1_1_main_conv_bn_bias, ema_detector_backbone_stage1_1_main_conv_bn_running_mean, ema_detector_backbone_stage1

2023-12-15 12:32:06,752 - mmdet - INFO - image shape: height=800, width=1440 in YOLOX.__init__
2023-12-15 12:32:06,777 - /webapps/piglegsurgery/piglegcv/incision_detection_mmdet.py - INFO - initialize YOLOX with init_cfg {'type': 'Pretrained', 'checkpoint': 'https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_x_8x8_300e_coco/yolox_x_8x8_300e_coco_20211126_140254-1ef88d67.pth'}
2023-12-15 12:32:06,778 - mmcv - INFO - load model from: https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_x_8x8_300e_coco/yolox_x_8x8_300e_coco_20211126_140254-1ef88d67.pth
2023-12-15 12:32:06,778 - mmcv - INFO - load checkpoint from http path: https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_x_8x8_300e_coco/yolox_x_8x8_300e_coco_20211126_140254-1ef88d67.pth
2023-12-15 12:32:07,015 - mmcv - WARNING - The model and loaded state dict do not match exactly

size mismatch for bbox_head.multi_level_conv_cls.0.weight: copying a param with shape torch.Size([80, 320, 1, 1]) from checkpoint, t

load checkpoint from local path: /webapps/piglegsurgery/piglegcv/resources/tracker_model_bytetrack_hands_tools/epoch_2.pth


2023-12-15 12:32:07.997 | DEBUG    | run_tracker_bytetrack:main_tracker_bytetrack:54 - Processing frame 0 by tracker


The model and loaded state dict do not match exactly

unexpected key in source state_dict: ema_detector_backbone_stem_conv_conv_weight, ema_detector_backbone_stem_conv_bn_weight, ema_detector_backbone_stem_conv_bn_bias, ema_detector_backbone_stem_conv_bn_running_mean, ema_detector_backbone_stem_conv_bn_running_var, ema_detector_backbone_stem_conv_bn_num_batches_tracked, ema_detector_backbone_stage1_0_conv_weight, ema_detector_backbone_stage1_0_bn_weight, ema_detector_backbone_stage1_0_bn_bias, ema_detector_backbone_stage1_0_bn_running_mean, ema_detector_backbone_stage1_0_bn_running_var, ema_detector_backbone_stage1_0_bn_num_batches_tracked, ema_detector_backbone_stage1_1_main_conv_conv_weight, ema_detector_backbone_stage1_1_main_conv_bn_weight, ema_detector_backbone_stage1_1_main_conv_bn_bias, ema_detector_backbone_stage1_1_main_conv_bn_running_mean, ema_detector_backbone_stage1_1_main_conv_bn_running_var, ema_detector_backbone_stage1_1_main_conv_bn_num_batches_tracked, ema_detector_ba

2023-12-15 12:32:19.374 | DEBUG    | run_tracker_bytetrack:main_tracker_bytetrack:54 - Processing frame 50 by tracker
2023-12-15 12:32:30.788 | DEBUG    | run_tracker_bytetrack:main_tracker_bytetrack:54 - Processing frame 100 by tracker
2023-12-15 12:32:42.341 | DEBUG    | run_tracker_bytetrack:main_tracker_bytetrack:54 - Processing frame 150 by tracker
2023-12-15 12:32:54.175 | DEBUG    | run_tracker_bytetrack:main_tracker_bytetrack:54 - Processing frame 200 by tracker
2023-12-15 12:33:05.991 | DEBUG    | run_tracker_bytetrack:main_tracker_bytetrack:54 - Processing frame 250 by tracker
2023-12-15 12:33:17.650 | DEBUG    | run_tracker_bytetrack:main_tracker_bytetrack:54 - Processing frame 300 by tracker
2023-12-15 12:33:29.499 | DEBUG    | run_tracker_bytetrack:main_tracker_bytetrack:54 - Processing frame 350 by tracker
2023-12-15 12:33:41.459 | DEBUG    | run_tracker_bytetrack:main_tracker_bytetrack:54 - Processing frame 400 by tracker
2023-12-15 12:33:53.435 | DEBUG    | run_tracker_

In [12]:
# report_data = dcv.make_report()